app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, db/schema.rb
@coleopard, can you please view my work ?
=> ui kit home

app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/pages/home.html.erb, config/environments/production.rb, db/schema.rb
@coleopard, j'ai fait toute la config NDD et SSL, et j'avais une modif à faire sur le fichier de config de prod.
Peux-tu valider stp ? :)
=> ssl config

.gitignore, Gemfile, Gemfile.lock, app/controllers/movies_controller.rb, app/models/movie.rb, config/environments/development.rb, config/storage.yml, db/migrate/20191126102638_create_active_storage_tables.active_storage.rb, db/schema.rb, db/seeds.rb
=> 2 movies seeds and 3 resized images each 250x250

app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/controllers/movies_controller.rb, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, app/views/movies/show.html.erb
@coleopard please review the top of the show.
=> show infos

app/assets/stylesheets/pages/_show.scss, app/controllers/movies_controller.rb, app/views/movies/show.html.erb
@coleopard, please review the show
=> show showtimes

.gitignore, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_index_movie.scss, app/views/movies/_best_deal.html.erb, app/views/movies/_card.html.erb, app/views/movies/index.html.erb, db/seeds.rb
@coleopard or @Castrax can you guyz have a look on my PR please?
Many thanks
=> index-front and back fix

app/assets/stylesheets/components/_navbar.scss, app/controllers/movies_controller.rb, app/javascript/packs/application.js, app/models/theater.rb, app/views/shared/_navbar.html.erb
=> modifs soir

Gemfile, Gemfile.lock, app/views/shared/_best_deal_index.html.erb, app/views/shared/_card_index.html.erb, config/environments/development.rb
Reverts Castrax/Showtime-app#17
=> Revert "links created"

Gemfile, app/views/movies/index.html.erb
=> Indextoshow link2

app/views/movies/show.html.erb, app/views/shared/_best_deal_index.html.erb, app/views/shared/_card_index.html.erb
=> ratings with stars full and blanks

app/controllers/movies_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/geoloc.js, app/views/shared/_navbar.html.erb
=> geoloc dans navbar

app/views/movies/show.html.erb
=> modales en fonction du showtime

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_show.scss, app/views/movies/show.html.erb, app/views/shared/_navbar.html.erb
=> navbar and show styling

Gemfile, Gemfile.lock, app/controllers/movies_controller.rb, app/models/theater.rb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
=> geoloc index

app/controllers/movies_controller.rb, app/javascript/plugins/geoloc.js, app/views/pages/home.html.erb
=> geolocation

app/controllers/application_controller.rb, app/controllers/movies_controller.rb
=> application

app/assets/stylesheets/components/_card.scss, app/views/shared/_card_index.html.erb, app/views/shared/_navbar.html.erb
=> arrow linkto show  + styling on index

app/controllers/movies_controller.rb, app/javascript/plugins/geoloc.js, app/views/shared/_navbar.html.erb
=> geoloc bug

config/environments/production.rb
=> config cloud

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> navbar stuff. It's better for spacing but still a bit ugly

Gemfile, Gemfile.lock, db/seeds.rb
=> photo cloud

db/seeds.rb
=> photo seed

Gemfile, Gemfile.lock, app/controllers/orders_controller.rb, app/controllers/payments_controller.rb, app/models/order.rb, app/models/user.rb, app/views/movies/show.html.erb, app/views/orders/show.html.erb, app/views/payments/new.html.erb, app/views/payments/show.html.erb, config/initializers/stripe.rb, config/routes.rb, db/migrate/20191128143337_create_orders.rb, db/schema.rb, db/seeds.rb, test/controllers/orders_controller_test.rb, test/controllers/payments_controller_test.rb, test/models/order_test.rb
@coleopard @Castrax @jonathansanturbano 
STRIPE IN DA PLACE GUYZ
=> STRIPE DONE BABY

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_show.scss, app/views/shared/_card_index.html.erb
=> hearts everywhere

app/views/pages/favorite.html.erb
=> byyyyyyyyyyyye

app/javascript/packs/application.js, app/javascript/plugins/heart_like.js
=> js fixed for hearts and modal mechanism

app/javascript/packs/application.js, app/javascript/plugins/calculate_price.js, app/views/shared/_modal.html.erb
=> jsfix no css index yet

app/javascript/plugins/init_carrousel.js
=> carrousel-config

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_show.scss, app/views/movies/show.html.erb, app/views/shared/_navbar.html.erb
=> navbar-change

app/assets/stylesheets/components/_card.scss
@jonathansanturbano another PR dude
=> fav position

app/controllers/orders_controller.rb, app/javascript/plugins/calculate_price.js, app/views/shared/_modal.html.erb
=> order amount updates with modal total price from show

app/assets/stylesheets/pages/_index_movie.scss
@jonathansanturbano some adjustments thx
=> index margin

app/assets/stylesheets/pages/_show.scss, app/controllers/orders_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/calculate_price.js, app/javascript/plugins/heart_like.js, app/views/shared/_modal.html.erb
@coleopard NE PAS MERGER JUSQU'A DEMAIN
=> modal and hearts work

app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/views/movies/index.html.erb, app/views/pages/home.html.erb
=> Rebranding

app/assets/stylesheets/pages/_home.scss
Changement couleur placeholder et couleur du contour du champ de recherche @Castrax
=> changes on index

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_index_movie.scss, app/views/shared/_navbar.html.erb
=> css in progress

app/assets/stylesheets/components/_card_showtimes.scss, app/assets/stylesheets/components/_index.scss, app/views/showtimes/show.html.erb
@jonathansanturbano @Castrax 
WIP
=> in progress

app/assets/stylesheets/components/_ribbon.scss, app/views/shared/_card_showtime_bestdeal.html.erb
=> index improv

app/assets/stylesheets/pages/_index_movie.scss, app/javascript/plugins/init_carrousel.js, db/seeds.rb
=> carroussel

app/views/shared/_modal.html.erb, app/views/shared/_showtimes_cards.html.erb, app/views/showtimes/show.html.erb
=> fix stripe

app/assets/stylesheets/components/_card_showtimes.scss, app/views/showtimes/show.html.erb
=> better to read details on the showtimes show movie picture

app/assets/stylesheets/components/_card_showtimes.scss, app/assets/stylesheets/components/_ribbon.scss, app/javascript/packs/application.js, app/javascript/plugins/button_fixed.js, app/views/showtimes/show.html.erb
=> fixed anim

app/views/showtimes/show.html.erb
=> small correction

app/assets/stylesheets/components/_card_showtimes.scss, app/javascript/packs/application.js, app/views/showtimes/show.html.erb
@Castrax @coleopard @jonathansanturbano
=> POMPIER DU CSS

app/assets/stylesheets/components/_book-cta.scss, app/assets/stylesheets/components/_card_showtimes.scss, app/assets/stylesheets/pages/_modal.scss, app/assets/stylesheets/pages/_movies_show.scss, app/views/shared/_modal.html.erb
=> modal finish

app/views/showtimes/show.html.erb
=> fix back button

app/assets/stylesheets/components/_confirmation-booking-card.scss
@Castrax @coleopard @jonathansanturbano 
Css fix to center the wallet button
=> css fix centrer wallet
